spring:
  application:
    name: fwpt
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: fwpt
    url: jdbc:mysql://localhost:3306/fwpt?serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080
