spring:
  application:
    name: fwpt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: fwpt
    url: jdbc:mysql://localhost:3306/fwpt?serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 8180

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjzxy.fwpt.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.monitor.wisdom_monitor: debug
    org.springframework: warn


fileUploadPath: "G:\\img"

folderPath: "F:\\bishe\\fwpt\\src\\assets\\usersImg"

defaultImg: "F:\\bishe\\fwpt\\src\\assets\\usersImg/default.jpg"

#pagehelper分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

## Redis服务器地址，另外注意要开启Redis服务
#spring.redis.host:127.0.0.1
## Redis服务器连接端口
#spring.redis.port:6379
## Redis服务器连接密码（默认为空）
#spring.redis.password:123456
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active:8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait:-1
## 连接池中最大空闲连接
#spring.redis.jedis.pool.max-idle:8

