spring:
  application:
    name: fwpt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: fwpt
    url: jdbc:mysql://localhost:3306/fwpt?serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8180

# 日志配置
logging:
  level:
    com.monitor.wisdom_monitor: debug
    org.springframework: warn
