spring:
  application:
    name: fwpt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: fwpt
    url: jdbc:mysql://localhost:3306/fwpt?serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8180

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjzxy.fwpt.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    com.monitor.wisdom_monitor: debug
    org.springframework: warn


fileUploadPath: "F:\\图片\\"
